In [1]:
import numpy as np

## 1D convolution

In [3]:
arr = np.arange(3) + 1
arr

array([1, 2, 3])

In [68]:
x = np.array([3, 5, 7, 11])
x_padded = np.concatenate([np.zeros(1), x, np.zeros(1)])
x_padded

array([ 0.,  3.,  5.,  7., 11.,  0.])

In [62]:
padding = 4
padded = np.append(arr, np.zeros(padding))
print("Padded:", padded, sep='\n')
tiled = np.tile(padded, 4)
print("Tiled:", tiled, sep='\n')
trimmed = tiled[:tiled.shape[0]-padding]
print("Trimmed:", trimmed, sep='\n')
reshaped = np.reshape(np.expand_dims(trimmed, -1), (x.shape[0], x_padded.shape[0]))
print("Reshaped:", reshaped, sep='\n')

Padded:
[1. 2. 3. 0. 0. 0. 0.]
Tiled:
[1. 2. 3. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 1. 2. 3.
 0. 0. 0. 0.]
Trimmed:
[1. 2. 3. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 1. 2. 3.]
Reshaped:
[[1. 2. 3. 0. 0. 0.]
 [0. 1. 2. 3. 0. 0.]
 [0. 0. 1. 2. 3. 0.]
 [0. 0. 0. 1. 2. 3.]]


In [69]:
np.matmul(reshaped, x_padded)

array([21., 34., 52., 29.])

## 1D Transpose convolution

In [71]:
np.matmul(reshaped.T, x)

array([ 3., 11., 26., 40., 43., 33.])

## 2D Convolution

In [139]:
x = np.array([1, 2, 3, 5, 7, 11, 13, 17, 19]).reshape((3, 3))
print(x)
x_padded = np.pad(x, (1, 1))
x_padded

[[ 1  2  3]
 [ 5  7 11]
 [13 17 19]]


array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  0],
       [ 0,  5,  7, 11,  0],
       [ 0, 13, 17, 19,  0],
       [ 0,  0,  0,  0,  0]])

In [151]:
windows = np.lib.stride_tricks.sliding_window_view(x_padded, (3, 3))
print("Windows shape:", windows.shape)
print("First window:", windows[0, 0], sep="\n")

Windows shape: (3, 3, 3, 3)
First window:
[[0 0 0]
 [0 1 2]
 [0 5 7]]


In [128]:
kernel = np.ones((3, 3))
kernel

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Guide to `np.einsum`: https://ajcr.net/Basic-guide-to-einsum/

In [137]:
np.einsum('ij, klij -> kl', kernel, windows)

array([[15., 29., 23.],
       [45., 78., 59.],
       [42., 72., 54.]])